[phases.setup]
nixPkgs = [
    "php84",
    "php84Extensions.fileinfo",
    "php84Extensions.mbstring",
    "php84Extensions.pdo",
    "php84Extensions.pdo_pgsql",
    "php84Extensions.bcmath",
    "php84Extensions.openssl",
    "php84Extensions.tokenizer",
    "composer",
    "nodejs",
    "npm"
]

[phases.build]
cmds = [
    "composer install --no-dev --prefer-dist --no-interaction --no-progress",
    "npm install",
    "npm run build",
    "php artisan config:cache",
    "php artisan event:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]
